# Generated by Django 4.2.5 on 2023-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.TextField()),
                ('simplified', models.TextField()),
                ('english', models.TextField()),
                ('pinyin', models.TextField()),
            ],
            options={
                'unique_together': {('traditional', 'simplified', 'english', 'pinyin')},
            },
        ),
    ]
