# Generated by Django 4.2.4 on 2023-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chParse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='charWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=1)),
                ('simplified', models.CharField(max_length=1)),
                ('pinyin', models.CharField(max_length=1)),
                ('english', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
